
package by.nbrb;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.6b21 Generated
 * source version: 2.0
 * 
 */
@WebServiceClient(name = "ExRates", targetNamespace = "http://www.nbrb.by/", wsdlLocation = "http://www.nbrb.by/Services/ExRates.asmx?WSDL")
public class ExRates extends Service {

    private final static URL EXRATES_WSDL_LOCATION;
    private final static WebServiceException EXRATES_EXCEPTION;
    private final static QName EXRATES_QNAME = new QName("http://www.nbrb.by/", "ExRates");

    static {
        /*
         * EXRATES_WSDL_LOCATION = by.nbrb.ExRates.class.getResource(
         * "http://www.nbrb.by/Services/ExRates.asmx?WSDL"); WebServiceException
         * e = null; if (EXRATES_WSDL_LOCATION == null) { e = new
         * WebServiceException(
         * "Cannot find 'http://www.nbrb.by/Services/ExRates.asmx?WSDL' wsdl. Place the resource correctly in the classpath."
         * ); } EXRATES_EXCEPTION = e;
         */
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.nbrb.by/Services/ExRates.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EXRATES_WSDL_LOCATION = url;
        EXRATES_EXCEPTION = e;

    }

    public ExRates() {
        super(__getWsdlLocation(), EXRATES_QNAME);
    }

    public ExRates(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return returns ExRatesSoap
     */
    @WebEndpoint(name = "ExRatesSoap")
    public ExRatesSoap getExRatesSoap() {
        return super.getPort(new QName("http://www.nbrb.by/", "ExRatesSoap"), ExRatesSoap.class);
    }

    /**
     * 
     * @return returns ExRatesSoap
     */
    @WebEndpoint(name = "ExRatesSoap12")
    public ExRatesSoap getExRatesSoap12() {
        return super.getPort(new QName("http://www.nbrb.by/", "ExRatesSoap12"), ExRatesSoap.class);
    }

    private static URL __getWsdlLocation() {
        if (EXRATES_EXCEPTION != null) {
            throw EXRATES_EXCEPTION;
        }
        return EXRATES_WSDL_LOCATION;
    }

}
