
package by.nbrb;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.6b21 Generated
 * source version: 2.0
 * 
 */
@WebService(name = "ExRatesSoap", targetNamespace = "http://www.nbrb.by/")
public interface ExRatesSoap {

    /**
     * ���������� �����
     * 
     * @return returns
     *         by.nbrb.CurrenciesRefDailyResponse.CurrenciesRefDailyResult
     */
    @WebMethod(operationName = "CurrenciesRefDaily", action = "http://www.nbrb.by/CurrenciesRefDaily")
    @WebResult(name = "CurrenciesRefDailyResult", targetNamespace = "http://www.nbrb.by/")
    @RequestWrapper(localName = "CurrenciesRefDaily", targetNamespace = "http://www.nbrb.by/", className = "by.nbrb.CurrenciesRefDaily")
    @ResponseWrapper(localName = "CurrenciesRefDailyResponse", targetNamespace = "http://www.nbrb.by/", className = "by.nbrb.CurrenciesRefDailyResponse")
    public by.nbrb.CurrenciesRefDailyResponse.CurrenciesRefDailyResult currenciesRefDaily();

    /**
     * ���������� �����
     * 
     * @return returns
     *         by.nbrb.CurrenciesRefMonthlyResponse.CurrenciesRefMonthlyResult
     */
    @WebMethod(operationName = "CurrenciesRefMonthly", action = "http://www.nbrb.by/CurrenciesRefMonthly")
    @WebResult(name = "CurrenciesRefMonthlyResult", targetNamespace = "http://www.nbrb.by/")
    @RequestWrapper(localName = "CurrenciesRefMonthly", targetNamespace = "http://www.nbrb.by/", className = "by.nbrb.CurrenciesRefMonthly")
    @ResponseWrapper(localName = "CurrenciesRefMonthlyResponse", targetNamespace = "http://www.nbrb.by/", className = "by.nbrb.CurrenciesRefMonthlyResponse")
    public by.nbrb.CurrenciesRefMonthlyResponse.CurrenciesRefMonthlyResult currenciesRefMonthly();

    /**
     * ��������� ���� ������������ ������������ ������ ���������� ��������
     * ������������ ����� ������������ ����� �� ��������� � ����������� �������
     * 
     * @param periodicity
     * @return returns javax.xml.datatype.XMLGregorianCalendar
     */
    @WebMethod(operationName = "StartDate", action = "http://www.nbrb.by/StartDate")
    @WebResult(name = "StartDateResult", targetNamespace = "http://www.nbrb.by/")
    @RequestWrapper(localName = "StartDate", targetNamespace = "http://www.nbrb.by/", className = "by.nbrb.StartDate")
    @ResponseWrapper(localName = "StartDateResponse", targetNamespace = "http://www.nbrb.by/", className = "by.nbrb.StartDateResponse")
    public XMLGregorianCalendar startDate(
            @WebParam(name = "Periodicity", targetNamespace = "http://www.nbrb.by/") int periodicity);

    /**
     * ��������� ���� ������������ ������������ ������ ���������� ��������
     * ������������ ����� ������������ ����� �� ��������� � ����������� �������
     * �� ���������� ������
     * 
     * @return returns javax.xml.datatype.XMLGregorianCalendar
     */
    @WebMethod(operationName = "LastDailyExRatesDate", action = "http://www.nbrb.by/LastDailyExRatesDate")
    @WebResult(name = "LastDailyExRatesDateResult", targetNamespace = "http://www.nbrb.by/")
    @RequestWrapper(localName = "LastDailyExRatesDate", targetNamespace = "http://www.nbrb.by/", className = "by.nbrb.LastDailyExRatesDate")
    @ResponseWrapper(localName = "LastDailyExRatesDateResponse", targetNamespace = "http://www.nbrb.by/", className = "by.nbrb.LastDailyExRatesDateResponse")
    public XMLGregorianCalendar lastDailyExRatesDate();

    /**
     * ��������� ���� ������������ ������������ ������ ���������� ��������
     * ������������ ����� ������������ ����� �� ��������� � ����������� �������
     * �� ����������� ������
     * 
     * @return returns javax.xml.datatype.XMLGregorianCalendar
     */
    @WebMethod(operationName = "LastMonthlyExRatesDate", action = "http://www.nbrb.by/LastMonthlyExRatesDate")
    @WebResult(name = "LastMonthlyExRatesDateResult", targetNamespace = "http://www.nbrb.by/")
    @RequestWrapper(localName = "LastMonthlyExRatesDate", targetNamespace = "http://www.nbrb.by/", className = "by.nbrb.LastMonthlyExRatesDate")
    @ResponseWrapper(localName = "LastMonthlyExRatesDateResponse", targetNamespace = "http://www.nbrb.by/", className = "by.nbrb.LastMonthlyExRatesDateResponse")
    public XMLGregorianCalendar lastMonthlyExRatesDate();

    /**
     * Официальный курс белорусского рубля по отношению к иностранным валютам,
     * устанавливаемый Национальным банком Республики Беларусь ежедневно, а
     * также до 17.02.1997 г.
     * 
     * @param onDate
     * @return returns by.nbrb.ExRatesDailyResponse.ExRatesDailyResult
     */
    @WebMethod(operationName = "ExRatesDaily", action = "http://www.nbrb.by/ExRatesDaily")
    @WebResult(name = "ExRatesDailyResult", targetNamespace = "http://www.nbrb.by/")
    @RequestWrapper(localName = "ExRatesDaily", targetNamespace = "http://www.nbrb.by/", className = "by.nbrb.ExRatesDaily")
    @ResponseWrapper(localName = "ExRatesDailyResponse", targetNamespace = "http://www.nbrb.by/", className = "by.nbrb.ExRatesDailyResponse")
    public by.nbrb.ExRatesDailyResponse.ExRatesDailyResult exRatesDaily(
            @WebParam(name = "onDate", targetNamespace = "http://www.nbrb.by/") XMLGregorianCalendar onDate);

    /**
     * ����������� ���� ������������ ����� �� ��������� � ����������� �������,
     * ��������������� ������������ ������ ���������� �������� ����������
     * 
     * @param onDate
     * @return returns by.nbrb.ExRatesMonthlyResponse.ExRatesMonthlyResult
     */
    @WebMethod(operationName = "ExRatesMonthly", action = "http://www.nbrb.by/ExRatesMonthly")
    @WebResult(name = "ExRatesMonthlyResult", targetNamespace = "http://www.nbrb.by/")
    @RequestWrapper(localName = "ExRatesMonthly", targetNamespace = "http://www.nbrb.by/", className = "by.nbrb.ExRatesMonthly")
    @ResponseWrapper(localName = "ExRatesMonthlyResponse", targetNamespace = "http://www.nbrb.by/", className = "by.nbrb.ExRatesMonthlyResponse")
    public by.nbrb.ExRatesMonthlyResponse.ExRatesMonthlyResult exRatesMonthly(
            @WebParam(name = "onDate", targetNamespace = "http://www.nbrb.by/") XMLGregorianCalendar onDate);

    /**
     * �������� ������������ ����� ������������ ����� �� ��������� � ��������
     * ����������� ������, ���������������� ������������ ������ ����������
     * �������� (�� ����� ��� �� 365 ����)
     * 
     * @param fromDate
     * @param curId
     * @param toDate
     * @return returns by.nbrb.ExRatesDynResponse.ExRatesDynResult
     */
    @WebMethod(operationName = "ExRatesDyn", action = "http://www.nbrb.by/ExRatesDyn")
    @WebResult(name = "ExRatesDynResult", targetNamespace = "http://www.nbrb.by/")
    @RequestWrapper(localName = "ExRatesDyn", targetNamespace = "http://www.nbrb.by/", className = "by.nbrb.ExRatesDyn")
    @ResponseWrapper(localName = "ExRatesDynResponse", targetNamespace = "http://www.nbrb.by/", className = "by.nbrb.ExRatesDynResponse")
    public by.nbrb.ExRatesDynResponse.ExRatesDynResult exRatesDyn(
            @WebParam(name = "curId", targetNamespace = "http://www.nbrb.by/") int curId,
            @WebParam(name = "fromDate", targetNamespace = "http://www.nbrb.by/") XMLGregorianCalendar fromDate,
            @WebParam(name = "toDate", targetNamespace = "http://www.nbrb.by/") XMLGregorianCalendar toDate);

    /**
     * ������ �������� ����������� �����, � ������� ����������� ����
     * ������������ ����� ��������������� ������������ ������ ����������
     * ��������
     * 
     * @param periodicity
     * @return returns by.nbrb.CurrenciesRefResponse.CurrenciesRefResult
     */
    @WebMethod(operationName = "CurrenciesRef", action = "http://www.nbrb.by/CurrenciesRef")
    @WebResult(name = "CurrenciesRefResult", targetNamespace = "http://www.nbrb.by/")
    @RequestWrapper(localName = "CurrenciesRef", targetNamespace = "http://www.nbrb.by/", className = "by.nbrb.CurrenciesRef")
    @ResponseWrapper(localName = "CurrenciesRefResponse", targetNamespace = "http://www.nbrb.by/", className = "by.nbrb.CurrenciesRefResponse")
    public by.nbrb.CurrenciesRefResponse.CurrenciesRefResult currenciesRef(
            @WebParam(name = "Periodicity", targetNamespace = "http://www.nbrb.by/") int periodicity);

    /**
     * ��������� ���� ������������ ������������ ������ ���������� �������� ���
     * �� ����������� ������� � ���� ���������� �������
     * 
     * @return returns javax.xml.datatype.XMLGregorianCalendar
     */
    @WebMethod(operationName = "MetalsLastDate", action = "http://www.nbrb.by/MetalsLastDate")
    @WebResult(name = "MetalsLastDateResult", targetNamespace = "http://www.nbrb.by/")
    @RequestWrapper(localName = "MetalsLastDate", targetNamespace = "http://www.nbrb.by/", className = "by.nbrb.MetalsLastDate")
    @ResponseWrapper(localName = "MetalsLastDateResponse", targetNamespace = "http://www.nbrb.by/", className = "by.nbrb.MetalsLastDateResponse")
    public XMLGregorianCalendar metalsLastDate();

    /**
     * �������� ����������� ��������, �� ������� ������������ ������ ����������
     * �������� ��������������� ������� ����
     * 
     * @return returns by.nbrb.MetalsRefResponse.MetalsRefResult
     */
    @WebMethod(operationName = "MetalsRef", action = "http://www.nbrb.by/MetalsRef")
    @WebResult(name = "MetalsRefResult", targetNamespace = "http://www.nbrb.by/")
    @RequestWrapper(localName = "MetalsRef", targetNamespace = "http://www.nbrb.by/", className = "by.nbrb.MetalsRef")
    @ResponseWrapper(localName = "MetalsRefResponse", targetNamespace = "http://www.nbrb.by/", className = "by.nbrb.MetalsRefResponse")
    public by.nbrb.MetalsRefResponse.MetalsRefResult metalsRef();

    /**
     * �������� ������� ��� �� ����������� ������� � ���� ���������� �������,
     * ��������������� ������������ ������ ���������� �������� (�� �����, ��� ��
     * 31 ����)
     * 
     * @param fromDate
     * @param metalId
     * @param toDate
     * @return returns by.nbrb.MetalsPricesResponse.MetalsPricesResult
     */
    @WebMethod(operationName = "MetalsPrices", action = "http://www.nbrb.by/MetalsPrices")
    @WebResult(name = "MetalsPricesResult", targetNamespace = "http://www.nbrb.by/")
    @RequestWrapper(localName = "MetalsPrices", targetNamespace = "http://www.nbrb.by/", className = "by.nbrb.MetalsPrices")
    @ResponseWrapper(localName = "MetalsPricesResponse", targetNamespace = "http://www.nbrb.by/", className = "by.nbrb.MetalsPricesResponse")
    public by.nbrb.MetalsPricesResponse.MetalsPricesResult metalsPrices(
            @WebParam(name = "MetalId", targetNamespace = "http://www.nbrb.by/") int metalId,
            @WebParam(name = "fromDate", targetNamespace = "http://www.nbrb.by/") XMLGregorianCalendar fromDate,
            @WebParam(name = "toDate", targetNamespace = "http://www.nbrb.by/") XMLGregorianCalendar toDate);

    /**
     * ���� ������� � ������� ������������ ������ ���������� ��������
     * ����������� �������� � ���� ������ �������
     * 
     * @param onDate
     * @return returns by.nbrb.IngotsPricesResponse.IngotsPricesResult
     */
    @WebMethod(operationName = "IngotsPrices", action = "http://www.nbrb.by/IngotsPrices")
    @WebResult(name = "IngotsPricesResult", targetNamespace = "http://www.nbrb.by/")
    @RequestWrapper(localName = "IngotsPrices", targetNamespace = "http://www.nbrb.by/", className = "by.nbrb.IngotsPrices")
    @ResponseWrapper(localName = "IngotsPricesResponse", targetNamespace = "http://www.nbrb.by/", className = "by.nbrb.IngotsPricesResponse")
    public by.nbrb.IngotsPricesResponse.IngotsPricesResult ingotsPrices(
            @WebParam(name = "onDate", targetNamespace = "http://www.nbrb.by/") XMLGregorianCalendar onDate);

    /**
     * ��������� ���� ������������ ������������ ������ ���������� �������� ���
     * ������� � ������� ����������� �������� � ���� ������ �������
     * 
     * @return returns javax.xml.datatype.XMLGregorianCalendar
     */
    @WebMethod(operationName = "IngotsLastDate", action = "http://www.nbrb.by/IngotsLastDate")
    @WebResult(name = "IngotsLastDateResult", targetNamespace = "http://www.nbrb.by/")
    @RequestWrapper(localName = "IngotsLastDate", targetNamespace = "http://www.nbrb.by/", className = "by.nbrb.IngotsLastDate")
    @ResponseWrapper(localName = "IngotsLastDateResponse", targetNamespace = "http://www.nbrb.by/", className = "by.nbrb.IngotsLastDateResponse")
    public XMLGregorianCalendar ingotsLastDate();

    /**
     * ���� ������������ ����� �� ��������� � �������� ����������� ������� ��
     * ������ �������������� �������� ������ ���
     * "����������� �������-�������� �����"
     * 
     * @param onDate
     * @return returns by.nbrb.StockAddRatesResponse.StockAddRatesResult
     */
    @WebMethod(operationName = "StockAddRates", action = "http://www.nbrb.by/StockAddRates")
    @WebResult(name = "StockAddRatesResult", targetNamespace = "http://www.nbrb.by/")
    @RequestWrapper(localName = "StockAddRates", targetNamespace = "http://www.nbrb.by/", className = "by.nbrb.StockAddRates")
    @ResponseWrapper(localName = "StockAddRatesResponse", targetNamespace = "http://www.nbrb.by/", className = "by.nbrb.StockAddRatesResponse")
    public by.nbrb.StockAddRatesResponse.StockAddRatesResult stockAddRates(
            @WebParam(name = "onDate", targetNamespace = "http://www.nbrb.by/") XMLGregorianCalendar onDate);

    /**
     * ��������� ���� ������������ ����� ������������ ����� �� ��������� �
     * �������� ����������� ������� �� ������ �������������� �������� ������ ���
     * "����������� �������-�������� �����"
     * 
     * @return returns javax.xml.datatype.XMLGregorianCalendar
     */
    @WebMethod(operationName = "StockAddRatesLastDate", action = "http://www.nbrb.by/StockAddRatesLastDate")
    @WebResult(name = "StockAddRatesLastDateResult", targetNamespace = "http://www.nbrb.by/")
    @RequestWrapper(localName = "StockAddRatesLastDate", targetNamespace = "http://www.nbrb.by/", className = "by.nbrb.StockAddRatesLastDate")
    @ResponseWrapper(localName = "StockAddRatesLastDateResponse", targetNamespace = "http://www.nbrb.by/", className = "by.nbrb.StockAddRatesLastDateResponse")
    public XMLGregorianCalendar stockAddRatesLastDate();

    /**
     * ������ ���������������� ������������� ����� �� ����
     * 
     * @param onDate
     * @return returns by.nbrb.RefRateOnDateResponse.RefRateOnDateResult
     */
    @WebMethod(operationName = "RefRateOnDate", action = "http://www.nbrb.by/RefRateOnDate")
    @WebResult(name = "RefRateOnDateResult", targetNamespace = "http://www.nbrb.by/")
    @RequestWrapper(localName = "RefRateOnDate", targetNamespace = "http://www.nbrb.by/", className = "by.nbrb.RefRateOnDate")
    @ResponseWrapper(localName = "RefRateOnDateResponse", targetNamespace = "http://www.nbrb.by/", className = "by.nbrb.RefRateOnDateResponse")
    public by.nbrb.RefRateOnDateResponse.RefRateOnDateResult refRateOnDate(
            @WebParam(name = "onDate", targetNamespace = "http://www.nbrb.by/") XMLGregorianCalendar onDate);

    /**
     * �������� ������ ���������������� ������������� �����
     * 
     * @return returns by.nbrb.RefRateDynResponse.RefRateDynResult
     */
    @WebMethod(operationName = "RefRateDyn", action = "http://www.nbrb.by/RefRateDyn")
    @WebResult(name = "RefRateDynResult", targetNamespace = "http://www.nbrb.by/")
    @RequestWrapper(localName = "RefRateDyn", targetNamespace = "http://www.nbrb.by/", className = "by.nbrb.RefRateDyn")
    @ResponseWrapper(localName = "RefRateDynResponse", targetNamespace = "http://www.nbrb.by/", className = "by.nbrb.RefRateDynResponse")
    public by.nbrb.RefRateDynResponse.RefRateDynResult refRateDyn();

}
